### ISSUE TITLE
Scale: X2

### ISSUE THREAD

**Issue by Moaazallaham** [Vishal2188/TherISuRNet---A-Computationally-Efficient-Thermal-Image-Super-Resolution-Network#2]
Hello Vishal,

Can you tell me what changes I need to do in order to achieve a scale of 2 or 3 instead of 4?

Thanks in advance.

**Comment by Vishal2188** [comment]
Changes you have to make in main.py file:
1) Put the corresponding LR and HR images in train_lr and train_hr folders
2) line number 75 : t = tf.placeholder(tf.float32, [bs, img_size*3, img_size*3, 3])
3) line number 149 : X_ = cv2.resize(X_,(img_size*2*3,img_size*2*3),interpolation = cv2.INTER_CUBIC)

Changes you have to make in model.py file:
1) line number 81 : x = tf.depth_to_space(x, 3)
2) line number 95 : x_GRL = tf.image.resize_bicubic(x, size=[h * 3, w * 3], align_corners=False, name=None)
3) line number 114-115 : xUP = self.Upsample2xBlock(x4, kernel_size=3, filters=63*3*3, strides = 1)
4) Remove line numbers: 129-130 and replace the teminology x6 with x5 in line number 132 

Changes you have to make in btgen.py file:
1) line number 17: self.HRSize = (img_size*3,img_size*3)
2) line number 41: new_y = img_y[y*3:y*3+self.HRSize[0], x*3:x*3+self.HRSize[1]]

The same changes for upscaling factor 2; just replace the letter 3 with 2. One additional change you have to make when dealing with upscaling factor 2. However, this change you have to made only when you are using the Domo PBVS training dataset. The change is below:

Line number: 39 - replace this sentence 
y = np.random.randint(0, h - self.LRSize[0]-1) with 
y = np.random.randint(0, self.LRSize[0]-1 - h)

This change you have to do because of the image size of the Domo PBVS training dataset. As the size of that dataset is very small so that you have to make the above change.

**Comment by Moaazallaham** [comment]
Thank you so much for your detailed explanation. 

It worked! :)
